# Application Name
spring.application.name=vehicle-service-booking-api

# Server Port
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=false
server.servlet.context-path=/vehiclserviceapi

#local
spring.datasource.url=jdbc:postgresql://localhost:5432/bike_service_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.default_schema=public

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.drop-first=false
spring.liquibase.contexts=dev
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public
spring.liquibase.database-change-log-table=databasechangelog
spring.liquibase.database-change-log-lock-table=databasechangeloglock

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-token.expiration=3600000
jwt.refresh-token.expiration=604800000

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Payment Gateway - Stripe
stripe.api.key=sk_test_your_stripe_secret_key
stripe.webhook.secret=whsec_your_webhook_secret

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.bookingapp=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param

# CORS Configuration
#app.cors.allowed-origins=http://localhost:3000,http://localhost:4200

# Swagger/OpenAPI
# API Documentation (Swagger/OpenAPI)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.show-actuator=true

management.endpoints.web.exposure.include=health,info,metrics,liquibase
management.endpoint.health.show-details=when-authorized
management.endpoint.liquibase.enabled=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000
